Back: Back
Remove: Remove
Save: Save
Upload: Upload

AddMedia: Add media

NoMediaFound: No media found.

MediaOverview: Media overview
NewMedia: New media

Information: File information
Preview: Preview
Location: File
NewFilename: New filename
Label: Label
Description: Description
UploadedOn: Uploaded on
Filename: Filename
FileContentType: Content type
FileLocation: File location

SaveSuccess label@Text: Successfully created: #{label}
UpdateSuccess label@Text: Successfully updated: #{label}
DeleteSuccess label@Text: Successfully deleted: #{label}
DeleteFail label@Text: Failed to delete: #{label}
