UserOverview: User overview
EmailAddress: E-mail address
NewUser: New user

PasswordTooShort: Password is too short
PasswordMismatch: Passwords don't match

Username: Username
Password: Password
Confirm: Confirm
Create: Create
Save: Save
Submit: Submit
Change: Change
Back: Back
Remove: Remove
CreatedOn: Created on
LastLogin: Last login
AccountActivationPending: Pending
AccountActivationSuccess: Activated

NoUsers: No users found
NoTUsers: There are no users

SuccessCreate: successfully created
SuccessReplace: Successfully replaced
SuccessUpdate:  Successfully updated
SuccessChgPwd:  Successfully changed password
SuccessDelete: Successfully deleted

DeletedUser u@Text: User #{u} deleted

TimeJustNow: Just now
TimeSecondsAgo time@String: #{time} seconds ago
TimeOneMinuteAgo: a minute ago
TimeMinutesAgo time@String: #{time} minutes ago
TimeOneHourAgo: an hour ago
TimeAboutHoursAgo time@String: about #{time} hours ago
TimeAt time@String: At #{time}
TimeDaysAgo time@String: #{time} days ago
TimeWeekAgo time@String: #{time} week ago
TimeWeeksAgo time@String: #{time} weeks ago
TimeOnYear time@String: on #{time}
DayOfWeekFmt: %l:%M %p on %A
