Back: Back
Remove: Remove
Save: Save
Upload: Upload

AddMedia: Add media

NoMediaFound: No media found.

MediaOverview: Media overview
NewMedia: New media

Preview: preview
Label: label
UploadedOn: uploaded on

SaveSuccess label@Text: Successfully created: #{label}
UpdateSuccess label@Text: Successfully updated: #{label}
DeleteSuccess label@Text: Successfully deleted: #{label}
DeleteFail label@Text: Failed to delete: #{label}
