UserOverview: Gebruikers overzicht
EmailAddress: E-mailadres

PasswordTooShort: Wachtwoord te kort
PasswordMismatch: Wachtwoorden komen niet overeen

Username: Gebruikersnaam
Password: Wachtwoord
Confirm: Bevestig
Create: Aanmaken
Save: Opslaan
Submit: Verzenden
Change: Aanpassen
Back: Terug
Remove: Verwijderen
AddUser: Gebruiker toevoegen
NewUser: Nieuwe gebruiker
CreatedOn: Geregistreerd op
LastLogin: Laatst ingelogd

NoUsers: Geen gebruikers gevonden
NoTUsers: Er zijn geen gebruikers

SuccessReplace: Succesvol aangepast
SuccessUpdate:  Succesvol geüpdatet
SuccessChgPwd:  Wachtwoord succesvol aangepast

DeletedUser u@Text: Gebruiker #{u} verwijderd

TimeJustNow: Nu net
TimeSecondsAgo time@String: #{time} seconden geleden
TimeOneMinuteAgo: een minuut geleden
TimeMinutesAgo time@String: #{time} minuten geleden
TimeOneHourAgo: een uur geleden
TimeAboutHoursAgo time@String: ongeveer #{time} uur geleden
TimeAt time@String: Om #{time}
TimeDaysAgo time@String: #{time} dagen geleden
TimeWeekAgo time@String: #{time} week geleden
TimeWeeksAgo time@String: #{time} weken geleden
TimeOnYear time@String: in #{time}
DayOfWeekFmt: %H:%M op %A
